import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Single source of truth: the backend's canonical catalog. The landing derives only the NUMBERS
// (price/gens/featured/id) from it at build time; bilingual marketing copy stays hand-authored in
// data/plans.ts. Ends landing↔app price drift (ADR 0006 §3, design-bridge P2).
const scriptDir = dirname(fileURLToPath(import.meta.url));
const catalogPath = join(scriptDir, "..", "..", "..", "packages", "payments", "src", "catalog-pricing.json");
const outPath = join(scriptDir, "..", "src", "data", "plans.generated.ts");

const catalog = JSON.parse(readFileSync(catalogPath, "utf8"));

const annualCents = (cents) => Math.round(cents * 0.8);
const formatBRL = (cents) => {
  const value = cents / 100;
  return Number.isInteger(value) ? `R$ ${value}` : `R$ ${value.toFixed(2).replace(".", ",")}`;
};
const formatUSD = (cents) => {
  const value = cents / 100;
  return Number.isInteger(value) ? `$${value}` : `$${value.toFixed(2)}`;
};

const generated = catalog.plans
  .filter((plan) => plan.priceCents)
  .map((plan) => ({
    id: plan.id,
    name: plan.name,
    featured: Boolean(plan.featured),
    priceValue: plan.priceCents.BRL / 100,
    monthlyGenerations: plan.monthlyGenerations,
    price: {
      brl: { monthly: formatBRL(plan.priceCents.BRL), annual: formatBRL(annualCents(plan.priceCents.BRL)) },
      usd: { monthly: formatUSD(plan.priceCents.USD), annual: formatUSD(annualCents(plan.priceCents.USD)) }
    }
  }));

const body = `// AUTO-GENERATED by scripts/sync-plans.mjs from packages/payments/src/catalog-pricing.json.
// Do not edit by hand — regenerated on every dev/build. Numbers are backend-SSOT; copy lives in plans.ts.
import type { PlanId } from "../config";

export interface GeneratedPlanNumbers {
  readonly id: PlanId;
  readonly name: string;
  readonly featured: boolean;
  readonly priceValue: number;
  readonly monthlyGenerations: number;
  readonly price: {
    readonly brl: { readonly monthly: string; readonly annual: string };
    readonly usd: { readonly monthly: string; readonly annual: string };
  };
}

export const GENERATED_PLAN_NUMBERS: readonly GeneratedPlanNumbers[] = ${JSON.stringify(generated, null, 2)};
`;

writeFileSync(outPath, body);
console.log(`sync-plans: wrote ${generated.length} plans to src/data/plans.generated.ts`);
