// AUTO-GENERATED by scripts/sync-plans.mjs from packages/payments/src/catalog-pricing.json.
// Do not edit by hand — regenerated on every dev/build. Numbers are backend-SSOT; copy lives in plans.ts.
import type { PlanId } from "../config";

export interface GeneratedPlanNumbers {
  readonly id: PlanId;
  readonly name: string;
  readonly featured: boolean;
  readonly priceValue: number;
  readonly monthlyGenerations: number;
  readonly price: {
    readonly brl: { readonly monthly: string; readonly annual: string };
    readonly usd: { readonly monthly: string; readonly annual: string };
  };
}

export const GENERATED_PLAN_NUMBERS: readonly GeneratedPlanNumbers[] = [
  {
    "id": "explorador",
    "name": "Explorador",
    "featured": false,
    "priceValue": 49,
    "monthlyGenerations": 15,
    "price": {
      "brl": {
        "monthly": "R$ 49",
        "annual": "R$ 39,20"
      },
      "usd": {
        "monthly": "$9",
        "annual": "$7.20"
      }
    }
  },
  {
    "id": "criador",
    "name": "Criador",
    "featured": true,
    "priceValue": 99,
    "monthlyGenerations": 30,
    "price": {
      "brl": {
        "monthly": "R$ 99",
        "annual": "R$ 79,20"
      },
      "usd": {
        "monthly": "$19",
        "annual": "$15.20"
      }
    }
  },
  {
    "id": "profissional",
    "name": "Profissional",
    "featured": false,
    "priceValue": 249,
    "monthlyGenerations": 80,
    "price": {
      "brl": {
        "monthly": "R$ 249",
        "annual": "R$ 199,20"
      },
      "usd": {
        "monthly": "$49",
        "annual": "$39.20"
      }
    }
  }
];
